import React from 'react';
import {
  siReact,
  siVercel,
  siPhp,
  siLaravel,
  siJavascript,
  siTailwindcss,
  siTypescript,
  siNextdotjs,
  siMongodb,
  siPostgresql,
  siPython,
  siMysql,
  siHtml5,
  siCss,
  siC,
  siCplusplus,
  siFirebase,
  siSupabase,
  siCloudflare,
  siDigitalocean,
  siGooglecloud,
  siWordpress,
  siElementor,
  siAstro,
  siTauri,
  siThreedotjs,
  siZod,
  siClaude,
  siGooglegemini,
  siWoocommerce,
} from 'simple-icons';

// helper func to create react component from simple-icons data
const create_icon_comp = (icon_data: { path: string; hex: string }) => {
  const IconComp: React.FC<React.SVGProps<SVGSVGElement>> = props =>
    React.createElement(
      'svg',
      {
        role: 'img',
        viewBox: '0 0 24 24',
        xmlns: 'http://www.w3.org/2000/svg',
        ...props,
      },
      React.createElement('path', { d: icon_data.path })
    );

  return IconComp;
};

interface TechIcon {
  Icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  name: string;
  color: string;
  x: number;
  y: number;
  z: number;
  id: string;
  order: number;
}

export const techIcons: TechIcon[] = [
  {
    Icon: create_icon_comp(siJavascript),
    name: 'JavaScript',
    color: `#${siJavascript.hex}`,
    x: 60,
    y: 60,
    z: -1500,
    id: 'javascript',
    order: 1,
  },
  {
    Icon: create_icon_comp(siReact),
    name: 'React',
    color: `#${siReact.hex}`,
    x: -120,
    y: -90,
    z: -1450,
    id: 'react',
    order: 2,
  },
  {
    Icon: create_icon_comp(siTypescript),
    name: 'TypeScript',
    color: `#${siTypescript.hex}`,
    x: -60,
    y: 120,
    z: -1400,
    id: 'typescript',
    order: 3,
  },
  {
    Icon: create_icon_comp(siNextdotjs),
    name: 'Next.js',
    color: `#${siNextdotjs.hex}`,
    x: 90,
    y: -120,
    z: -1350,
    id: 'nextdotjs',
    order: 4,
  },
  {
    Icon: create_icon_comp(siTailwindcss),
    name: 'Tailwind CSS',
    color: `#${siTailwindcss.hex}`,
    x: -180,
    y: 30,
    z: -1300,
    id: 'tailwindcss',
    order: 5,
  },
  {
    Icon: create_icon_comp(siMongodb),
    name: 'MongoDB',
    color: `#${siMongodb.hex}`,
    x: 0,
    y: 150,
    z: -1250,
    id: 'mongodb',
    order: 6,
  },
  {
    Icon: create_icon_comp(siPostgresql),
    name: 'PostgreSQL',
    color: `#${siPostgresql.hex}`,
    x: -90,
    y: -150,
    z: -1200,
    id: 'postgresql',
    order: 7,
  },
  {
    Icon: create_icon_comp(siLaravel),
    name: 'Laravel',
    color: `#${siLaravel.hex}`,
    x: -150,
    y: -30,
    z: -1150,
    id: 'laravel',
    order: 8,
  },
  {
    Icon: create_icon_comp(siMysql),
    name: 'MySQL',
    color: `#${siMysql.hex}`,
    x: 210,
    y: -90,
    z: -1100,
    id: 'mysql',
    order: 9,
  },
  {
    Icon: create_icon_comp(siPython),
    name: 'Python',
    color: `#${siPython.hex}`,
    x: -150,
    y: 90,
    z: -1050,
    id: 'python',
    order: 10,
  },
  {
    Icon: create_icon_comp(siPhp),
    name: 'PHP',
    color: `#${siPhp.hex}`,
    x: 180,
    y: 60,
    z: -1000,
    id: 'php',
    order: 11,
  },
  {
    Icon: create_icon_comp(siC),
    name: 'C',
    color: `#${siC.hex}`,
    x: 120,
    y: 120,
    z: -950,
    id: 'c',
    order: 12,
  },
  {
    Icon: create_icon_comp(siCplusplus),
    name: 'C++',
    color: `#${siCplusplus.hex}`,
    x: -100,
    y: -180,
    z: -900,
    id: 'cplusplus',
    order: 13,
  },
  {
    Icon: create_icon_comp(siVercel),
    name: 'Vercel',
    color: `#${siVercel.hex}`,
    x: 150,
    y: -30,
    z: -850,
    id: 'vercel',
    order: 14,
  },
  {
    Icon: create_icon_comp(siHtml5),
    name: 'HTML5',
    color: `#${siHtml5.hex}`,
    x: 0,
    y: -180,
    z: -800,
    id: 'html5',
    order: 15,
  },
  {
    Icon: create_icon_comp(siCss),
    name: 'CSS3',
    color: `#${siCss.hex}`,
    x: 180,
    y: 180,
    z: -750,
    id: 'css',
    order: 16,
  },
  {
    Icon: create_icon_comp(siFirebase),
    name: 'Firebase',
    color: `#${siFirebase.hex}`,
    x: -180,
    y: 180,
    z: -700,
    id: 'firebase',
    order: 17,
  },
  {
    Icon: create_icon_comp(siSupabase),
    name: 'Supabase',
    color: `#${siSupabase.hex}`,
    x: 200,
    y: 0,
    z: -650,
    id: 'supabase',
    order: 18,
  },
  {
    Icon: create_icon_comp(siCloudflare),
    name: 'Cloudflare',
    color: `#${siCloudflare.hex}`,
    x: -200,
    y: 0,
    z: -600,
    id: 'cloudflare',
    order: 19,
  },
  {
    Icon: create_icon_comp(siDigitalocean),
    name: 'DigitalOcean',
    color: `#${siDigitalocean.hex}`,
    x: 70,
    y: 200,
    z: -550,
    id: 'digitalocean',
    order: 20,
  },
  {
    Icon: create_icon_comp(siGooglecloud),
    name: 'Google Cloud',
    color: `#${siGooglecloud.hex}`,
    x: -70,
    y: -200,
    z: -500,
    id: 'googlecloud',
    order: 21,
  },
  {
    Icon: create_icon_comp(siWordpress),
    name: 'WordPress',
    color: `#${siWordpress.hex}`,
    x: 220,
    y: -100,
    z: -450,
    id: 'wordpress',
    order: 22,
  },
  {
    Icon: create_icon_comp(siElementor),
    name: 'Elementor',
    color: `#${siElementor.hex}`,
    x: -220,
    y: 100,
    z: -400,
    id: 'elementor',
    order: 23,
  },
  {
    Icon: create_icon_comp(siAstro),
    name: 'Astro',
    color: `#${siAstro.hex}`,
    x: 160,
    y: -160,
    z: -350,
    id: 'astro',
    order: 24,
  },
  {
    Icon: create_icon_comp(siTauri),
    name: 'Tauri',
    color: `#${siTauri.hex}`,
    x: -160,
    y: 160,
    z: -300,
    id: 'tauri',
    order: 25,
  },
  {
    Icon: create_icon_comp(siThreedotjs),
    name: 'Three.js',
    color: `#${siThreedotjs.hex}`,
    x: 100,
    y: -200,
    z: -250,
    id: 'threedotjs',
    order: 26,
  },
  {
    Icon: create_icon_comp(siZod),
    name: 'Zod',
    color: `#${siZod.hex}`,
    x: -100,
    y: 200,
    z: -200,
    id: 'zod',
    order: 27,
  },
  {
    Icon: create_icon_comp(siClaude),
    name: 'Claude AI',
    color: `#${siClaude.hex}`,
    x: 240,
    y: 50,
    z: -150,
    id: 'claude',
    order: 28,
  },
  {
    Icon: create_icon_comp(siGooglegemini),
    name: 'Gemini',
    color: `#${siGooglegemini.hex}`,
    x: -240,
    y: -50,
    z: -100,
    id: 'googlegemini',
    order: 29,
  },
  {
    Icon: create_icon_comp(siWoocommerce),
    name: 'WooCommerce',
    color: `#${siWoocommerce.hex}`,
    x: -260,
    y: 80,
    z: -50,
    id: 'woocommerce',
    order: 30,
  },
].sort((a, b) => a.order - b.order);
